server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5002/auth_db_dev}
    username: ${DB_USERNAME:auth_user}
    password: ${DB_PASSWORD:auth_pass}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

security:
  jwt:
    secret: dGhpcyBpcyBhIDUxMi1iaXQgc2VjcmV0IGtleSBmb3IgSFM1MTIgand0IHNpZ25pbmcgYWxnb3JpdGhtIGVuY29kZWQgaW4gYmFzZTY0IGZvcm1hdCB0aGF0IHlvdSBjYW4gdXNlIGZvciBzZWN1cmUgdG9rZW4=
    access-token-expiration: 1800000 # 30 minutes for dev
    refresh-token-expiration: 86400000 # 1 day for dev

  oauth2:
    client:
      registration:
        google:
          client-id: dev-google-client-id
          client-secret: dev-google-client-secret
          redirect-uri: http://localhost:8081/auth-service/login/oauth2/code/google

  password:
    policy:
      min-length: 8 # Relaxed for development
      max-age-days: 365 # Relaxed for development

  mfa:
    enabled: false # Disabled for easier development

  session:
    timeout: 3600 # 1 hour for development
    max-concurrent: 10 # More sessions allowed in dev

rate-limiting:
  login-attempts:
    max-attempts: 10 # More attempts in dev
    block-duration: 60 # Only 1 minute block in dev

services:
  tenant-service:
    url: http://localhost:8080
  authorization-service:
    url: http://localhost:8082
  notification-service:
    url: http://localhost:8085

logging:
  level:
    root: INFO
    com.nnipa.auth: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.saml: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  file:
    name: logs/auth-service-dev.log

# Development-specific features
debug: true

# Swagger UI enabled
springdoc:
  swagger-ui:
    enabled: true
    try-it-out-enabled: true

# Extended actuator endpoints for development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always