package com.nnipa.auth.enums;

public enum AuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    PASSWORD_CHANGE,
    PASSWORD_RESET,
    MFA_ENABLED,
    MFA_DISABLED,
    MFA_CHANGE,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    TOKEN_REFRESH,
    SESSION_CREATED,
    SESSION_EXPIRED,
    PERMISSION_DENIED,
    OAUTH_LOGIN,
    SAML_LOGIN,
    ACCOUNT_ACTIVATED,
    ACCOUNT_DEACTIVATED,
    USER_REGISTERED,
    MFA_REQUIRED
}