package com.nnipa.auth.enums;

public enum SecurityEventType {
    BRUTE_FORCE_ATTACK,
    SUSPICIOUS_ACTIVITY,
    ACCOUNT_TAKEOVER_ATTEMPT,
    INVALID_TOKEN_USE,
    CONCURRENT_SESSION_LIMIT,
    GEO_LOCATION_ANOMALY,
    UNUSUAL_ACCESS_PATTERN,
    DATA_BREACH_ATTEMPT,
    PRIVILEGE_ESCALATION_ATTEMPT,
    MFA_BYPASS_ATTEMPT
}